### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Ignotus** [fgoujeon/scalpel#2]
http://paste.pocoo.org/show/391987/

**Comment by fgoujeon** [comment]
Regarding the errors implying unique_ptr_vector, I guess there's a regression in GCC since the calls to std::move() could be safely removed (the object is created inline, which makes it an r-value). Anyway, I worked it around by separating the object declaration and its addition in the vector.

Regarding the compilation errors implying simple_function and simple_member_function, I can't see any error in the code. std::move() is implied here again.
I hope those errors are caused by the previous ones. Otherwise, it means that the C++0x support of your compiler is outdated.

Could you update your local repository and retry?

**Comment by Ignotus** [comment]
Yes, I installed gcc 4.6

**Comment by seb777** [comment]
For your information, scalpel (commit https://github.com/fgoujeon/scalpel/commit/18349cade325e792901563fe231a3e470ba32346) compiles with g++ (GCC) 4.6.0 20110513 (prerelease) without error.

**Comment by fgoujeon** [comment]
Fine, I close the report.
